# This file was generated by GoReleaser. DO NOT EDIT.
class Fsrpl < Formula
  desc "fsrpl is CloudFirestore replication tool."
  homepage "https://github.com/matsu0228/fsrpl"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/matsu0228/fsrpl/releases/download/v0.0.2/fsrpl_0.0.2_darwin_amd64.tar.gz"
    sha256 "26bc32b81f5966e992854d83bfe4f8404f32a7a7648b84e91ddfc5c338813522"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/matsu0228/fsrpl/releases/download/v0.0.2/fsrpl_0.0.2_linux_amd64.tar.gz"
      sha256 "b21ede7e606e2663ba50be89197b69ce0e60c74aef5d9649d276191fc2af7b22"
    end
  end

  def install
    bin.install Dir['fsrpl']
    zsh_completion.install "misc/completions/zsh/_fsrpl"
  end

  test do
    system "#{bin}/fsrpl"
  end
end
